# Generated by Django 5.2.1 on 2025-05-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fieldchangelog_sessionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('create', 'Create'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other'), ('export', 'Export'), ('2fa_enable', '2FA Enabled'), ('2fa_disable', '2FA Disabled'), ('2fa_verify', '2FA Verified'), ('session_revoke', 'Session Revoked')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='FieldChangeLog',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
