# Generated by Django 5.2.1 on 2025-05-26 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schedulableresource_ward_user_language_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=64, unique=True)),
                ('test_name', models.CharField(max_length=255)),
                ('specimen_type', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_for_lab', models.TextField(blank=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.laborder')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labtestcatalog')),
            ],
        ),
        migrations.CreateModel(
            name='LabResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=128)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, max_length=128)),
                ('units', models.CharField(blank=True, max_length=32)),
                ('reference_range_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference_range_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('abnormal_flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('result_timestamp', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lab_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.laborderitem')),
            ],
        ),
    ]
