# Generated by Django 5.2.1 on 2025-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_labtestcatalog_laborderitem_labresultvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcatalog',
            name='critical_range_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='critical_range_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
