# Generated by Django 5.2.1 on 2025-05-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_labtestcatalog_critical_range_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('create', 'Create'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other'), ('export', 'Export'), ('session_revoke', 'Session Revoked')], max_length=32),
        ),
    ]
