# Generated by Django 5.2.1 on 2025-06-17 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_schedule', models.BooleanField(default=False)),
                ('can_view_data', models.BooleanField(default=True)),
                ('can_act_as_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
