# Generated by Django 5.2.6 on 2025-09-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appointment_google_calendar_synced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleoauthcredentials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='google_calendar_synced',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='google_event_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='google_sync_timestamp',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Token',
                'verbose_name_plural': 'Google Calendar Tokens',
            },
        ),
        migrations.DeleteModel(
            name='GoogleCalendarSettings',
        ),
        migrations.DeleteModel(
            name='GoogleOAuthCredentials',
        ),
    ]
